export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_GENRES = 'FETCH_GENRES';
export const SET_FAVOURITE = 'SET_FAVOURITE';
export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';